title: The Pinnacle Group
subtitle: Insurance & Financial Services
agent: David Jimenez, LUTCF, CSA
location: 1099 E. Champlain Dr. Apt. 149
city: Fresno
state: CA
zipCode: 93720
phoneNumber: (559)307-3085
faxNumber: (559)900-7949
contactEmail: jimenez748@aol.com
